[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim.git"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  [".config/nvim".pull]
    args = ["--ff-only"]

[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  [".tmux/plugins/tpm".pull]
    args = ["--ff-only"]
