# Nord Light (Gogh)
# Source: https://github.com/Gogh-Co/Gogh/blob/master/themes/Nord%20Light.yml

background            #EBEAF2
foreground            #004F7C
cursor                #439ECF
cursor_text_color     #EBEAF2

selection_background  #439ECF
selection_foreground  #EBEAF2

url_color             #00B1BE

# Normal colors
color0  #003B4E
color1  #E64569
color2  #069F5F
color3  #DAB752
color4  #439ECF
color5  #D961DC
color6  #00B1BE
color7  #B3B3B3

# Bright colors
color8  #3E89A1
color9  #E4859A
color10 #A2CCA1
color11 #E1E387
color12 #6FBBE2
color13 #E586E7
color14 #96DCDA
color15 #DEDEDE
